apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    tier: backend
    app: redis
spec:
  volumes:
  - name: redis-data
    gcePersistentDisk:
      pdName: redisdb
      fsType: ext4
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data
  
