apiVersion: v1
kind: PersistentVolume
metadata:
  name: redisdata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: redisdb
    fsType: ext4
