apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador-deployment
  labels:
    app: contador
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: contador
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: contador
        tier: frontend
    spec:
      containers:
      - name: contador-python
        image: fams/contador:v1beta2
        ports:
        - containerPort: 5000
        env:
        - name:  REDIS_HOST
          value: redis.default.svc.cluster.local
        - name:  REDIS_PORT
          value: "6379"
